dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),                #后台管理模块
    url(r'^user/', include('user.urls', namespace='user')),   #用户模块
    url(r'^', include('goods.urls', namespace='goods')),      #首页模块
    url(r'^tinymce/', include('tinymce.urls')),               #tinymce
]

dailyfresh/user/urls.py
from django.conf.urls import url
from user import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^register$',views.RegisterView.as_view(),name='register'),#用户注册
    url(r'^login$',views.LoginView.as_view(),name='login'),#用户登录
    url(r'^loginout$',views.loginout,name='loginout'),#退出登录
    url(r'^change_passwd$', views.Change_passwdView.as_view(), name='change_passwd'),#修改密码
    url(r'^validate_code$',views.validate_code,name='validate_code'),#验证码
    url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(), name='active'),#用户激活

    #'''利用装饰器判定登录-方法1 (推荐)'''
    url(r'^$', views.UserInfoView.as_view(), name='user'), # 用户中心-信息页
    url(r'^order$', views.UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    url(r'^address$', views.UserAddressView.as_view(), name='address'),  # 用户中心-地址页

    #'''利用装饰器判定登录-方法2'''
    # url(r'^$', login_required(views.UserInfoView.as_view()), name='user'), # 用户中心-信息页
    # url(r'^order$', login_required(views.UserOrderView.as_view()), name='order'),  # 用户中心-订单页
    # url(r'^address$', login_required(views.UserAddressView.as_view()), name='address'),  # 用户中心-地址页

    #''省市县三级联动'''
    url(r'^get_all_province$', views.get_all_province, name='get_all_province'),
    url(r'^get_city_by_pid$', views.get_city_by_pid, name='get_city_by_pid'),
    url(r'^get_area_by_cid$', views.get_area_by_cid, name='get_area_by_cid'),

]

dailyfresh/templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-购物车</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods012.jpg"></li>
		<li class="col03">奇异果<br><em>25.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods003.jpg"></li>
		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">16.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">16.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="place_order.html">去结算</a></li>
	</ul>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

dailyfresh/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" >
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{remember_username}}"/>
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<input name="validate_code" class="validate_code_input" placeholder="请输入验证码"/>
                        <img id='validate_code_img' src="{% url 'user:validate_code'%}" class="validate_code_img" />
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1">
							<label>记住用户名</label>
							<a href="/user/change_passwd">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
				{{ error_name }}
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

<script>
    var validate_code_img=document.getElementById('validate_code_img')
    var url='/user/validate_code?num='
    validate_code_img.onclick=function () {
        var num=new Date().getTime()
        url+=num
        validate_code_img.src=url
    }
</script>

dailyfresh/templates/test_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for goodstype in goodstype_list %}
    <li>
        <ul>
            <li>{{ goodstype.name }}</li>
            <li><img src="{{ goodstype.image.url }}"></li>
        </ul>
    </li>
    {% endfor %}
</ul>

</body>
</html>

dailyfresh/templates/text1.html
<div class="person-data-place">
                <p>居住地:</p>
                <div id="city_4">
                        <select class="prov"></select>
                        <select class="city" disabled="disabled"></select>
                        <select class="dist" disabled="disabled"></select>
                </div>
</div>

dailyfresh/templates/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="/user/loginout">退出登录</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="/user/login">登录</a>
					<span>|</span>
					<a href="/user/register">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == '1' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == '2' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == '3' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							{% if address %}
							   <li><span>联系方式：</span>{{ address.phone }}</li>
							   <li><span>联系地址：</span>{{ address.address }}</li>
							{% else %}
							   <li><span>联系方式：</span>无默认</li>
							   <li><span>联系地址：</span>无默认</li>
							{% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="/static/images/goods/goods003.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods004.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods005.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods006.jpg"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods007.jpg"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

dailyfresh/templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="/user/loginout">退出登录</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="/user/login">登录</a>
					<span>|</span>
					<a href="/user/register">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == '1' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == '2' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == '3' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

dailyfresh/templates/user_center_site.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
        $(function(){
            //发送请求,显示所有的省份
            get_all_province()
            //为省绑定事件
            change_province()
            //为市绑定事件
            change_city()
        });
        function get_all_province() {
            $.ajax({
                url:'/user/get_all_province',
                success:function(data){
                   province_list = eval('('+data.province_list+')')
                    console.log(province_list)
                   $.each(province_list,function(index,item){
                       var option='<option value="'+item.pk+'">'+item.fields.pname+'</option>';
                       $('#province_id').append(option)
                   })
                }
            });
        };
        function change_province() {
             $('#province_id').change(function () {
                 province_id=$('#province_id').val();
                 console.log(province_id)
                 $('#city_id').html('<option value="0">------</option>')
                 $('#area_id').html('<option value="0">------</option>')
                 if(province_id==0){
                     $('#city_id').html('<option value="0">------</option>')
                     $('#area_id').html('<option value="0">------</option>')
                 }else {
                     $.ajax({
                        url:'/user/get_city_by_pid',
                        data:{'province_id':$('#province_id').val()},
                        success:function(data){
                               city_list = eval('('+data.city_list+')')
								console.log(city_list)
                               $('#city_id').html('<option value="0">------</option>')
                               $.each(city_list,function(index,item){
                                   var option='<option value="'+item.pk+'">'+item.fields.cname+'</option>';
                                   $('#city_id').append(option)
                               })
                        }
                     });
                 }
             });
        };
        function change_city() {
             $('#city_id').change(function () {
                 city_id=$('#city_id').val();
                 if(city_id==0){
                     $('#area_id').html('<option value="0">------</option>')
                 }else {
                     $.ajax({
                        url:'/user/get_area_by_cid',
                        data:{'city_id':city_id},
                        success:function(data){
                               area_list = eval('('+data.area_list+')')
							console.log(area_list)
                               $('#area_id').html('<option value="0">------</option>')
                               $.each(area_list,function(index,item){
                                   var option='<option value="'+item.pk+'">'+item.fields.aname+'</option>';
                                   $('#area_id').append(option)
                               })
                        }
                     });
                 }
             });
        };
    </script>

</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="/user/loginout">退出登录</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="/user/login">登录</a>
					<span>|</span>
					<a href="/user/register">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == '1' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == '2' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == '3' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<!--{% if address %}-->
						   <dd>{{ address.address}} （{{address.receiver}} 收） {{address.phone}}</dd>
						<!--{% else %}-->
						   <dd>无默认地址</dd>
						<!--{% endif %}-->
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/address" method="post">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver" value="{{ address.receiver }}">
						</div>
						<div>
							   省<select name="province_id" id="province_id"><option value="0">------</option></select>
							   市<select name="city_id" id="city_id"><option value="0">------</option></select>
							   区<select name="area_id" id=area_id><option value="0">------</option></select>
                        </div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address" id="bar">{{ address.address }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode" value="{{ address.postcode }}">{{ postcode_errmsg }}
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone" value="{{ address.phone }}">{{ phone_errmsg }}
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
					{{ errmsg }}
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>